name: builder

on:
  push:
    branches:    
      - master

jobs:
  deploy-to-github-page:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Init Node
      uses: actions/setup-node@v1 
      with:
        node-version: "12.x"

    - name: Build
      run: |
        yarn install
        yarn build

    - name: Deploy
      env:
        TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
      run: |
        cd dist
        # 初始化 git
        git init
        git config user.email "hopgoldy@gmail.com"
        git config user.name "CI Builder"
        # 生成并推送 commit
        git add .
        git commit -m "feat: UPDATE BY GITHUB ACTION"
        git push --quiet --force https://$TARGET_REPO_TOKEN@github.com/HoPGoldy/realworld-vue3-antd.git master:github-page